sonar.projectKey=SusovanDas19_Multi-Cloud-DevSecOps-Log-Analysis-Project
sonar.organization=susovandas19
sonar.projectName=LogGuard Monitoring Platform

# Source directories to scan
sonar.sources=log-monitoring-platform/apps/api/src,log-monitoring-platform/apps/web/src

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/.turbo/**,**/coverage/**,log-monitoring-platform/apps/ml/**,LogMonitoringAgent/**

# TypeScript
sonar.typescript.tsconfigPaths=log-monitoring-platform/apps/api/tsconfig.json,log-monitoring-platform/apps/web/tsconfig.app.json