apiVersion: apps/v1
kind: Deployment
metadata:
  name: logguard-api
  labels:
    app: logguard-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logguard-api
  template:
    metadata:
      labels:
        app: logguard-api
    spec:
      containers:
        - name: api
          image: DOCKER_USERNAME_PLACEHOLDER/logguard-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: JWT_SECRET
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: GEMINI_API_KEY
            - name: USE_AI_THREAT
              value: "false"
            - name: ML_SERVICE_URL
              value: "http://logguard-ml-service:8001/analyze-log-batch"
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: AWS_REGION
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: AWS_S3_BUCKET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: CORS_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: CORS_ORIGIN
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: logguard-api-service
  labels:
    app: logguard-api
spec:
  type: NodePort
  selector:
    app: logguard-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080