apiVersion: v1
kind: Secret
metadata:
  name: devsecops-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "DATABASE_URL_PLACEHOLDER"
  JWT_SECRET: "JWT_SECRET_PLACEHOLDER"
  GEMINI_API_KEY: "GEMINI_API_KEY_PLACEHOLDER"
  AWS_REGION: "AWS_REGION_PLACEHOLDER"
  AWS_S3_BUCKET: "AWS_S3_BUCKET_PLACEHOLDER"
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID_PLACEHOLDER"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY_PLACEHOLDER"
  CORS_ORIGIN: "CORS_ORIGIN_PLACEHOLDER"